In [24]:
import numpy as np

A = np.array([[-64,-55, 4, -5],[0, -55, 56, -3], [0, 0, 45, 35.5], [0,0,0,-53]])
print(A)

np.linalg.qr(A)


[[-64.  -55.    4.   -5. ]
 [  0.  -55.   56.   -3. ]
 [  0.    0.   45.   35.5]
 [  0.    0.    0.  -53. ]]


(array([[ 1.,  0.,  0.,  0.],
        [-0.,  1.,  0.,  0.],
        [-0., -0.,  1.,  0.],
        [-0., -0., -0.,  1.]]),
 array([[-64. , -55. ,   4. ,  -5. ],
        [  0. , -55. ,  56. ,  -3. ],
        [  0. ,   0. ,  45. ,  35.5],
        [  0. ,   0. ,   0. , -53. ]]))